### PR TITLE
Add CNCF Community Code of Conduct v1.3 in Armenian language

### PR DESCRIPTION
**Pull request by hayk96**
**What this PR does:**
- Adding `CNCF Community Code of Conduct v1.3` in Armenian language

### CODE REVIEW

**Comment by nate-double-u** [comment]
Hi @hayk96 thanks for this. Unfortunately we don't have the capacity to review this PR (I don't read Armenian). Is there a localization community you'd be able to wrangle to help with this? Several CNCF projects have localization teams, perhaps the Armenian team from one of those projects could come and help to confirm this translation?

**Comment by hayk96** [comment]
Thanks for your reply @nate-double-u. I'll try to find respective reviewers from the Armenian community reviewing this MR.

**Comment by nate-double-u** [comment]
Hi @hayk96, just following up, have you been able to find any reviewers? If not, perhaps you could reach out to the CNCF Glossary or Kubernetes localization groups, they may have some folks willing to help.

**Comment by krook** [comment]
> Hi @hayk96, just following up, have you been able to find any reviewers? If not, perhaps you could reach out to the CNCF Glossary or Kubernetes localization groups, they may have some folks willing to help.

@hayk96 thanks again for the contribution. Do you have an update on finding reviewers?

**Comment by nate-double-u** [comment]
Hi @hayk96, I'm going to close this as stale. Please feel free to re-open this if you're able to recruit some reviewers!

**Pull request closed without merging**
