### PR TITLE
Revert "Updating code of conduct translation: Ukrainian"

### PR DESCRIPTION
**Pull request by idvoretskyi**
Reverts cncf/foundation#774

Just noticed the pull request with the request to review. I've made a brief overview of the proposed PR, and noticed that it looks like an output of the automated translation tool or similar.

Therefore, I'd revert the proposed PR and will submit my edits afterwards.

### CODE REVIEW

**Comment by krook** [comment]
Are we able to close this PR now @idvoretskyi @nate-double-u?

**Comment by nate-double-u** [comment]
For translation/localization PRs I prefer to have at least 1 native speaker review -- however, since it's @idvoretskyi's translation I'm OK with merging it if he thinks it's good to go.

**Comment by nate-double-u** [comment]
(wait, I'm actually not sure what this PR is doing, does #786 supersede this PR?)

**Comment by krook** [comment]
Yeah, that's why this seemed unnecessary

**Comment by nate-double-u** [comment]
Closing as stale. @idvoretskyi, feel free to reopen if i've missed something.

**Pull request closed without merging**
