### PR TITLE
Typo in charter.md

### PR DESCRIPTION
**Pull request by asafm**
Fix tiny typo

### CODE REVIEW

**Comment by asafm** [comment]
Anybody monitoring PRs to this Repo?

**Comment by asafm** [comment]
@caniszczyk

**Review by idvoretskyi — APPROVED** [review]

**Comment by asafm** [comment]
@idvoretskyi Merge?

**Comment by idvoretskyi** [comment]
@caniszczyk PTAL

**Comment by asafm** [comment]
Nm

**Pull request closed without merging**
