### PR TITLE
AddKnative  WG leads to maintainers list

### PR DESCRIPTION
**Pull request by aliok**
As we decided in Knative community, we want to have the WG leads in the maintainers list: https://github.com/knative/community/issues/1383#issuecomment-1865809475

Added missing people from the list https://github.com/knative/community/blob/main/peribolos/knative-OWNERS_ALIASES

cc @puerco @salaboy @nainaz @evankanderson

### CODE REVIEW

**Review by evankanderson — APPROVED** [review]
/lgtm

**Comment by aliok** [comment]
@Cmierly 

Sorry I missed notifications for your message.

> could you send an email to [cncf-maintainer-changes@cncf.io](mailto:cncf-maintainer-changes@cncf.io) with info on the new maintainers?

Is there a document describing what kind of info you need?

**Comment by amye** [comment]
> @Cmierly
> 
> Sorry I missed notifications for your message.
> 
> > could you send an email to [cncf-maintainer-changes@cncf.io](mailto:cncf-maintainer-changes@cncf.io) with info on the new maintainers?
> 
> Is there a document describing what kind of info you need?

It's just a way to give us emails without publishing in GH

**Comment by aliok** [comment]
@Cmierly, I just sent that email now.

Thanks!

**Comment by dprotaso** [comment]
Hey @Cmierly seems like a few folks aren't receiving email on the member list - is there a way for Knative folks to audit the members and their emails?

**Comment by Cmierly** [comment]
Sure!
Here's the list of maintainers that have been invited and their acceptance
status
[image: image.png]

**Pull request merged**
