### PR TITLE
Update Metal3 project maintainers list

### PR DESCRIPTION
**Pull request by furkatgofurov7**
This PR updates [Metal3](https://metal3.io/) Sandbox project maintainers list which is synchronized with the latest all owners file [here](https://github.com/metal3-io/metal3-docs/blob/main/maintainers/ALL-OWNERS).

### CODE REVIEW

**Comment by amye** [comment]
Can you throw me a list of emails that have been added? amye@linuxfoundation.org will work fine.

**Comment by furkatgofurov7** [comment]
> Can you throw me a list of emails that have been added? [amye@linuxfoundation.org](mailto:amye@linuxfoundation.org) will work fine.

Thanks, sure I am collecting now all the emails of maintainers in the list, once collected will send them right away.

**Comment by furkatgofurov7** [comment]
> Thanks, sure I am collecting now all the emails of maintainers in the list, once collected will send them right away.

@amye email is sent

**Pull request merged**
