### PR TITLE
typo correction

### PR DESCRIPTION
**Pull request by SeanKnight**
`technical identify` doesn't make sense. Assuming it was supposed to be `technical identity` based on context.

### CODE REVIEW

**Comment by dankohn** [comment]
Thank you for the proposed fix. I agree that this is just a typo and needs to be fixed. However, we're trying to be rigorous in only changing the charter when the governing board votes to do so.

So, I'll include this fix in the next update the GB votes on, likely some time in 2020.

Cc @taylorwaggoner @idvoretskyi

**Comment by SeanKnight** [comment]
@dankohn so uh, how did the vote go?

**Comment by dims** [comment]
@SeanKnight we've had only a few updates since then and we lost track of this. Apologies.
https://github.com/cncf/foundation/commits/main/charter.md

Also unfortunately, @dankohn is no longer with us, if you wish to leave a note in his memory, please do so here:
https://github.com/cncf/memorials/blob/main/dan-kohn.md

**Comment by SeanKnight** [comment]
@dims Thank you for the update. The typo is still in the charter, should this be re-opened?

Also, so sad to hear about Dan, thanks for letting me know. 😢

**Pull request closed without merging**
