### PR TITLE
Add Inspektor Gadget maintainers

### PR DESCRIPTION
**Pull request by blixtra**
Adding Inspektor Gadget maintainers entry for new Sandbox project as per https://github.com/cncf/toc/issues/1021

### CODE REVIEW

**Comment by amye** [comment]
Needs affiliations, otherwise it'll break the table.

**Comment by amye** [comment]
@blixtra  - checking in here, this needs the affiliations for everyone otherwise it breaks the table!

**Comment by blixtra** [comment]
This has been updated. Please try again.

**Comment by amye** [comment]
Merged! If you can give us the maintainers emails to project-onboarding@cncf.io, we'd appreciate it. We'll be able to give you access to servicedesk with those.

**Pull request merged**
